- name: conditions demo
  hosts: local
  connection: local
  vars:
    NUMBER: 78
  tasks:
  - name: print if the number is less than or equal to 100
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is less than or equal to 100"
    when: NUMBER <= 100

  - name: print if the number is greater than 100
    ansible.builtin.debug:
      msg: "Given number {{ NUMBER }} is greater than 100"
    when: NUMBER > 100

- name: playbook control using ansible facts
  hosts: node
  become: yes
  tasks:
  - name: install nginx if redhat
    ansible.builtin.dnf:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: install nginx if debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"