- name: nginx install and run
  hosts: ansible
  become: yes # sudo access
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: nginx
      state: present
  
  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes